name: app_empresa_cliente
description: Aplicativo para clientes acessarem seus dados na empresa.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.0
  email_validator: ^2.0.1
  mask_text_input_formatter: ^2.0.0
  mailer: ^6.4.1
  flutter_email_sender: ^6.0.2

  # Design e UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0

  # Armazenamento e Preferências
  shared_preferences: ^2.2.0

  # Requisições HTTP e Comunicação
  http: ^1.1.0
  connectivity_plus: ^4.0.2

  # Formatação e Utilidades
  intl: ^0.19.0  # Atualizado para ^0.19.0
  url_launcher: ^6.1.12

  path_provider: ^2.0.11

  open_file: ^3.5.10
  flutter_pdfview: ^1.4.0

  flutter_switch: ^0.3.2
  flutter_localizations:
    sdk: flutter # Adicionado para suporte à localização

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/